like_dislike_using-ajax/sns_project/main/urls.py
from django.urls import path
from .views import *

app_name = "main"
urlpatterns = [

    path('',showmain, name="cover"),
    path('intro/',showintro, name="intro"),
    path('hobby/',showhobby, name="hobby"),
    path('food/',showfood, name="food"),
    path('netflix/',shownetflix, name="netflix"),
    path('new/',new, name="new"),
    path('create/', create, name="create"),
    path('<int:id>',showpost, name="showpost"),
    path('postlist/', postlist ,name="postlist"),
    path('edit/<int:id>', edit , name="edit"),
    path('update/<int:id>', update ,name="update"),
    path('delete/<int:id>', delete ,name="delete"),
    path('<int:post_id>/create_comment',create_comments,name="create_comments"),
    path('<int:post_id>/comment_edit/<int:comment_id>',comment_edit,name="comment_edit"),
    path('<int:post_id>/update_comments/<int:comment_id>',update_comments,name="update_comments"),
    path('<int:post_id>/delete_comments/<int:comment_id>',delete_comments,name="delete_comments"),
    path('like_toggle/<int:post_id>/',like_toggle, name="like_toggle"),
    path('dislike_toggle/<int:post_id>/',dislike_toggle, name="dislike_toggle"),
    

]

like_dislike_using-ajax/sns_project/sns_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('accounts/',include('allauth.urls')),
    path('users/',include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

like_dislike_using-ajax/sns_project/users/urls.py
from django.urls import path
from .views import *

app_name="users"

urlpatterns = [
    path('<int:id>/mypage/',mypage,name="mypage"),
    path('<int:id>/follow/',follow, name="follow"),
]

like_dislike_using-ajax/sns_project/sns_project/templates/shared/_nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
      aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">

        <a class="nav-link" href="{% url 'main:intro' %}">인적사항</a>
        <a class="nav-link" href="{% url 'main:hobby' %}">취미</a>
        <a class="nav-link" href="{% url 'main:food' %}">좋아하는 음식</a>
        <a class="nav-link" href="{% url 'main:netflix' %}">Netflix</a>
        <a class="nav-link" href="{% url 'main:new' %}">글쓰기</a>
        <a class="nav-link" href="{% url 'main:postlist' %}">글목록</a>


        {% if user.is_authenticated %}
        <a class="nav-link" href="{%url 'users:mypage' request.user.id %}">Mypage</a>
        <a class="nav-link" href="{%url 'account_logout'%}">Logout</a>
        {% else %}
        <a class="nav-link" href="{% url 'account_login' %}">Login</a>
        <a class="nav-link" href="{%url 'account_signup'%}">Signup</a>
        {% endif %}


      </div>
    </div>
  </div>
</nav>