like_dislike_using-ajax/sns_project/main/urls.py
from django.urls import path
from .views import *

app_name = "main"
urlpatterns = [

    path('',showmain, name="cover"),
    path('intro/',showintro, name="intro"),
    path('hobby/',showhobby, name="hobby"),
    path('food/',showfood, name="food"),
    path('netflix/',shownetflix, name="netflix"),
    path('new/',new, name="new"),
    path('create/', create, name="create"),
    path('<int:id>',showpost, name="showpost"),
    path('postlist/', postlist ,name="postlist"),
    path('edit/<int:id>', edit , name="edit"),
    path('update/<int:id>', update ,name="update"),
    path('delete/<int:id>', delete ,name="delete"),
    path('<int:post_id>/create_comment',create_comments,name="create_comments"),
    path('<int:post_id>/comment_edit/<int:comment_id>',comment_edit,name="comment_edit"),
    path('<int:post_id>/update_comments/<int:comment_id>',update_comments,name="update_comments"),
    path('<int:post_id>/delete_comments/<int:comment_id>',delete_comments,name="delete_comments"),
    path('like_toggle/<int:post_id>/',like_toggle, name="like_toggle"),
    path('dislike_toggle/<int:post_id>/',dislike_toggle, name="dislike_toggle"),
    

]

like_dislike_using-ajax/sns_project/sns_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('accounts/',include('allauth.urls')),
    path('users/',include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

like_dislike_using-ajax/sns_project/users/urls.py
from django.urls import path
from .views import *

app_name="users"

urlpatterns = [
    path('<int:id>/mypage/',mypage,name="mypage"),
    path('<int:id>/follow/',follow, name="follow"),
]

like_dislike_using-ajax/sns_project/users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save
# Create your models here.

class Profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    followings=models.ManyToManyField("self",related_name="followers",symmetrical=False)

@receiver(post_save, sender=User)
def create_user_prpofile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save,sender=User)
def save_user_profile(sender,instance,**kwargs):
    instance.profile.save()

like_dislike_using-ajax/sns_project/users/views.py
from django.shortcuts import render,get_object_or_404,redirect
from main.models import Post
from django.contrib.auth.models import User
# Create your views here.

def mypage(request,id):
    user=get_object_or_404(User,pk=id)
    context={
        'user':user,
        'posts':Post.objects.filter(writer=user),
        'followings':user.profile.followings.all(),
        'followers':user.profile.followers.all(),
    }
    return render(request,'users/mypage.html',context)

def follow(request,id):
    user=request.user
    followed_user=get_object_or_404(User,pk=id) 
    is_follower=user.profile in followed_user.profile.followers.all() 
    if is_follower:
        user.profile.followings.remove(followed_user.profile) 
    else:
        user.profile.followings.add(followed_user.profile) 
    return redirect('users:mypage', followed_user.id)

like_dislike_using-ajax/sns_project/users/templates/users/mypage.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="main">

    <div class="container">
        <br>
        <h1>
            {% if 'user' in user.username and user.username != 'user' %}
            {{ user.last_name }} {{ user.first_name }}
            {% else %}
            {{ user.username }}
            {% endif %}
        </h1>
        <h1>
            {% if request.user != user %}
            <!--다른 사람의 프로필에 들어온 경우에만 팔로우/언팔로우 버튼이보임--> {% if request.user.profile in user.profile.followers.all %}
            <a href="{%url 'users:follow' user.id %}"><button type="button"
                    class="btn btn-outline-info">언팔로우</button></a>
            {% else %}
            <a href="{%url 'users:follow' user.id %}"><button type="button" class="btn btn-info">팔로우</button></a>
            {% endif %} {% endif %}
        </h1>
        <div>
            <h3>팔로워{{user.profile.followers.count}}명</h3> {%for follower in user.profile.followers.all %}
            <a class="wc" href="{% url 'users:mypage' follower.user.id %}">{{follower.user.username}}</a> {% endfor %}
            <h3>팔로잉{{user.profile.followings.count}}명</h3> {% for following in user.profile.followings.all %}
            <a class="wc" href="{%url 'users:mypage' following.user.id%}">{{following.user.username}}</a> {% endfor %}
        </div>
        
        <div>
            <br>
            {% for post in posts %}
            <a class="wc" href="{%url 'main:showpost' post.id%}">{{post.title}}</a>
            <hr>
            {%endfor%}
        </div>
    </div>


    
    
</div>
{% endblock %}