aws/sns_project/main/urls.py
from django.urls import path
from .views import *

app_name = "main"
urlpatterns = [

    path('',showmain, name="cover"),
    path('intro/',showintro, name="intro"),
    path('hobby/',showhobby, name="hobby"),
    path('food/',showfood, name="food"),
    path('netflix/',shownetflix, name="netflix"),
    path('new/',new, name="new"),
    path('create/', create, name="create"),
    path('<int:id>',showpost, name="showpost"),
    path('postlist/', postlist ,name="postlist"),
    path('edit/<int:id>', edit , name="edit"),
    path('update/<int:id>', update ,name="update"),
    path('delete/<int:id>', delete ,name="delete"),
    path('<int:post_id>/create_comment',create_comments,name="create_comments"),
    path('<int:post_id>/comment_edit/<int:comment_id>',comment_edit,name="comment_edit"),
    path('<int:post_id>/update_comments/<int:comment_id>',update_comments,name="update_comments"),
    path('<int:post_id>/delete_comments/<int:comment_id>',delete_comments,name="delete_comments"),


]

aws/sns_project/main/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=200)
    writer = models.ForeignKey(User,on_delete=models.CASCADE)
    pub_date = models.DateTimeField()
    body = models.TextField()
    image = models.ImageField(upload_to = "post/", blank=True, null=True)
    
    def __str__(self):
        ans='{} {}'.format(self.title,self.id)
        return ans
    
    def summary(self):
        return self.body[:20]
class Comment(models.Model):
    content=models.TextField()
    writer=models.ForeignKey(User,on_delete=models.CASCADE)
    post=models.ForeignKey(Post,on_delete=models.CASCADE,related_name="comments")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

aws/sns_project/main/views.py
from django.shortcuts import render, redirect,get_object_or_404
from  .models import Post, Comment
from django.utils import timezone
import random
# Create your views here.

def showmain(request):
    return render(request, 'main/cover.html')

def postlist(request):
    posts=Post.objects.all()
    return render(request, 'main/postlist.html',{'posts':posts})

def showintro(request):
    return render(request, 'main/intro.html')

def showhobby(request):
    return render(request, 'main/hobby.html')

def shownetflix(request):
    return render(request, 'main/netflix.html')

def showfood(request):
    return render(request, 'main/food.html')
    
def showpost(request,id):
    post = get_object_or_404(Post, pk =id)
    all_comments = post.comments.all().order_by('-created_at')
    return render(request,'main/detail.html',{'post':post, 'comments':all_comments})

def new(request):
    return render(request,'main/new.html')

def create(request):
    new_post = Post()
    new_post.title=request.POST['title']
    new_post.writer=request.user
    new_post.pub_date=timezone.now()
    new_post.body=request.POST['body']
    new_post.image = request.FILES.get('image')
    new_post.save()
    return redirect('main:showpost',new_post.id)

def edit(request, id):
    edit_post=Post.objects.get(id=id)
    return render(request, 'main/edit.html',{'post':edit_post})

def update(request, id):
    update_post = Post.objects.get(id=id)
    update_post.title = request.POST['title']
    update_post.writer = request.user
    update_post.pub_date = timezone.now()
    update_post.body = request.POST['body']
    update_post.image = request.FILES.get('image')
    update_post.save()
   
    return redirect('main:showpost', update_post.id)

def delete(request,id):
    delete_blog = Post.objects.get(id=id)
    delete_blog.delete()
    return redirect('main:postlist')

def create_comments(request,post_id):
    new_comment=Comment()
    new_comment.content=request.POST['content']
    new_comment.writer=request.user
    new_comment.post=get_object_or_404(Post,pk=post_id)
    new_comment.save()
    return redirect('main:showpost',post_id)

def comment_edit(request,post_id,comment_id):
    edit_comment=Comment.objects.get(id=comment_id)
    return render(request, 'main/comment_edit.html',{'comment':edit_comment,'post_id':post_id})


def update_comments(request,post_id,comment_id):
    update_comment=Comment.objects.get(id=comment_id)
    update_comment.content=request.POST['content']
    update_comment.writer=request.user
    update_comment.post=get_object_or_404(Post,pk=post_id)
    update_comment.save()
    return redirect('main:showpost',update_comment.post.id)

   
def delete_comments(request,post_id,comment_id):
    
    delete_comment = Comment.objects.get(id=comment_id)
    delete_comment.delete()
    return redirect('main:showpost',post_id)

aws/sns_project/main/templates/main/detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="list">
    <h1>제목 : {{post.title}}</h1> <br>
    {% if post.writer %}
    {% if 'user' in post.writer.username and post.writer.username != 'user' %}
    작성자 : <a class='wc' href="{% url 'users:mypage' post.writer.id %}">{{ post.writer.last_name }} {{ post.writer.first_name }}</a>
    {% else %}
    작성자 : <a class='wc' href="{% url 'users:mypage' post.writer.id %}">{{ post.writer }}</a>
    {% endif %}
    {% else %}
    작성자 : 알 수 없음
    {% endif %}
    <br>

    날짜 : {{post.pub_date}} <br>
    {% if post.image %}
    <p><img src="{{post.image.url}}" alt="사진"></p>
    {% endif %}
    내용 : {{post.body}}
    <br>
    <a class='wc' href="{%url 'main:edit' post.id%}">수정하기</a>
    <a class='wc' href="{%url 'main:delete' post.id%}">삭제하기</a>
    <br>
    <br>
    <hr>
    <div>
        <form action="{%url 'main:create_comments' post.id %}" method="post">
            {%csrf_token%}

            <br><textarea name="content" placeholder="댓글 작성"></textarea>
            <button type="submit">확인</button>
        </form>
    </div>
    <br>
    <div style="padding:20px;">
        {% for comment in comments %}

        <p>{% if comment.writer %}
            {% if 'user' in comment.writer.username and comment.writer.username != 'user' %}
            작성자 : <a class='wc'
                href="{% url 'users:mypage' comment.writer.id %}">{{comment.writer.last_name }}{{ comment.writer.first_name }}</a>
            {% else %}
            작성자 : <a class='wc' href="{% url 'users:mypage' comment.writer.id %}">{{ comment.writer }}</a>
            {% endif %}
            {% else %}
            작성자 : 알 수 없음
            {% endif %}
        </p>
        작성일시 : {{comment.created_at}} &nbsp;
        수정일시 : {{comment.updated_at}}
        <br>
        <br>
        {{comment.content}}
        <br>
        <br>
        <a class='wc' href="{%url 'main:comment_edit' post.id comment.id %}">수정하기</a>
        <a class='wc' href="{%url 'main:delete_comments' post.id comment.id %}">삭제하기</a>
        <hr>
        {% endfor %}
    </div>
</div>




{% endblock %}